{
  BROWSER:
    chrome
    BASE_URL:
      https://prod.app.cosmosid.com
    ADMIN_BASE_URL:
      example_prod
      LOGIN_PAGE:
        https://api.cosmosid.com/login
      SUPPORTED_BROWSERS:
        [ "chrome", "firefox", "edge", "opera" ]
}